version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data

  redis-commander:
    platform: linux/amd64
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOST=redis
    ports:
    - "8081:8081"

  trottling-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    env_file: .env
