version: '3.8'

services:
  app:
    image: client-contractor-test
    container_name: client-contractor
    build: .
    ports: 
      - "3001:3001"
    volumes: 
      - .:/usr/src
      - /usr/src/node_modules